roles:
# Test is for basic smb deployment & functionality. one node cluster is OK
- - host.a
  - mon.a
  - mgr.x
  - osd.0
  - osd.1
  - client.0
# Reserve a host for acting as a domain controller
- - host.b
  - cephadm.exclude
tasks:
- cephadm.deploy_samba_ad_dc:
    role: host.b
- cephadm:

- cephadm.shell:
    host.a:
      - ceph fs volume create cephfs
- cephadm.wait_for_service:
    service: mds.cephfs

- cephadm.shell:
    host.a:
      # add subvolgroup & subvolumes for test
      - cmd: ceph fs subvolumegroup create cephfs smb
      - cmd: ceph fs subvolume create cephfs sv1 --group-name=smb --mode=0777
      - cmd: ceph fs subvolume create cephfs sv2 --group-name=smb --mode=0777
      # set up smb cluster and shares
      - cmd: ceph mgr module enable smb
      # TODO: replace sleep with poll of mgr state?
      - cmd: sleep 30
      - cmd: ceph smb apply -i -
        stdin: |
          # --- Begin Embedded YAML
          - resource_type: ceph.smb.cluster
            cluster_id: modtest1
            auth_mode: active-directory
            domain_settings:
              realm: DOMAIN1.SINK.TEST
              join_sources:
                - source_type: resource
                  ref: join1-admin
            custom_dns:
              - "192.168.76.204"
            placement:
              count: 1
          - resource_type: ceph.smb.join.auth
            auth_id: join1-admin
            auth:
              username: Administrator
              password: Passw0rd
          - resource_type: ceph.smb.share
            cluster_id: modtest1
            share_id: share1
            cephfs:
              volume: cephfs
              subvolumegroup: smb
              subvolume: sv1
              path: /
          - resource_type: ceph.smb.share
            cluster_id: modtest1
            share_id: share2
            cephfs:
              volume: cephfs
              subvolumegroup: smb
              subvolume: sv2
              path: /
          # --- End Embedded YAML
# Wait for the smb service to start
- cephadm.wait_for_service:
    service: smb.modtest1
# Check if shares exist
- cephadm.exec:
    host.b:
      - sleep 30
      - "{{ctx.samba_client_container_cmd|join(' ')}} smbclient -U DOMAIN1\\\\ckent%1115Rose. //{{'host.a'|role_to_remote|attr('ip_address')}}/share1 -c ls"
      - "{{ctx.samba_client_container_cmd|join(' ')}} smbclient -U DOMAIN1\\\\ckent%1115Rose. //{{'host.a'|role_to_remote|attr('ip_address')}}/share2 -c ls"
